Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: datasets in /home/sacchin/.local/lib/python3.10/site-packages (2.13.1)
Requirement already satisfied: fsspec[http]>=2021.11.1 in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (2023.6.0)
Requirement already satisfied: pyyaml>=5.1 in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (6.0)
Requirement already satisfied: pyarrow>=8.0.0 in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (12.0.1)
Requirement already satisfied: numpy>=1.17 in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (1.24.1)
Requirement already satisfied: requests>=2.19.0 in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (2.28.1)
Requirement already satisfied: dill<0.3.7,>=0.3.0 in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (0.3.6)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.11.0 in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (0.16.4)
Requirement already satisfied: pandas in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (2.0.2)
Requirement already satisfied: tqdm>=4.62.1 in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (4.65.0)
Requirement already satisfied: xxhash in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (3.2.0)
Requirement already satisfied: multiprocess in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (0.70.14)
Requirement already satisfied: aiohttp in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (3.8.4)
Requirement already satisfied: packaging in /home/sacchin/.local/lib/python3.10/site-packages (from datasets) (23.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /home/sacchin/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in /home/sacchin/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.3)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /home/sacchin/.local/lib/python3.10/site-packages (from aiohttp->datasets) (4.0.2)
Requirement already satisfied: attrs>=17.3.0 in /home/sacchin/.local/lib/python3.10/site-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /home/sacchin/.local/lib/python3.10/site-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: aiosignal>=1.1.2 in /home/sacchin/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /home/sacchin/.local/lib/python3.10/site-packages (from aiohttp->datasets) (2.1.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/sacchin/.local/lib/python3.10/site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (4.7.1)
Requirement already satisfied: filelock in /home/sacchin/.local/lib/python3.10/site-packages (from huggingface-hub<1.0.0,>=0.11.0->datasets) (3.9.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/sacchin/.local/lib/python3.10/site-packages (from requests>=2.19.0->datasets) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /home/sacchin/.local/lib/python3.10/site-packages (from requests>=2.19.0->datasets) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /home/sacchin/.local/lib/python3.10/site-packages (from requests>=2.19.0->datasets) (3.4)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas->datasets) (2022.1)
Requirement already satisfied: tzdata>=2022.1 in /home/sacchin/.local/lib/python3.10/site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/sacchin/.local/lib/python3.10/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
